
FROM nginx:alpine

COPY index.html /usr/share/nginx/html/

EXPOSE 80

# docker build -t web .
# docker run --name test3 -p 8080:80 web
# docker build -t web01 src/web01/Dockerfile
# docker run --name test3 -p 4000:80 web
